esphome:
  name: quatt-sniffer
  friendly_name: QMBus

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable Home Assistant API
api:
  encryption:
    key: !secret QMB_api

ota:
  - platform: esphome
    password: !secret QMB_ota

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  #ap:
  #  ssid: "QMBus_AP"
  #  password: !secret QMB_AP

#captive_portal:
    
external_components:
  # use all components from a local folder
  - source:
      type: local
      path: my_components
    components: [ modbus, modbus_controller]

# Enable logging
logger:
  #baud_rate: 0                         ## Igor Ybema: make sure to turn of logging via UART (set baudrate to 0) as the RS485 uses the onboard UART (tx/rx)
  level: DEBUG
  logs:
    uart_debug: DEBUG                  ## toon uart_debug data wel
    modbus: DEBUG                      ## onderdruk log-berichten van modbus
    modbus_controller.sensor: ERROR    ## onderdruk log-berichten van modbus_controller

# Configuratie van UART op Quatt modbus connectie-parameters
uart:                 ## Igor Ybema: The RS485 is connected to the ESP32-C3 via hardware uart, rx/tx (gpio20/gpio21).
  id: uart_bus
  # tx_pin: GPIO21    ## just listening: tx_pin not specified  BUT must kill TX output hardware trace anyway!
  rx_pin: GPIO23      ## on ESP32C3 use GPIO20, on ESP32 use GPIO23
  baud_rate: 19200    ## start bit na 52us: 19200 baud zie https://discord.com/chann...24364/1232080954466631761
  data_bits: 8
  parity: EVEN
  stop_bits: 1
#  debug:
#    after: 
#      timeout: 10ms
#    sequence:
#      - lambda: UARTDebug::log_hex(direction, bytes, ',');    ## toon modbus data als hex waarden in uart_debug log

# Configuratie modbus in ESPHome
modbus:
  uart_id: uart_bus
  id: mod_bus

# Configuratie modbus_controller voor wegschrijven Quatt modbus-data uit uart naar HA-sensoren
modbus_controller:
- id: modbus_device_1
  address: 1              ## address of the Modbus slave device on the bus
  modbus_id: mod_bus
  update_interval: 10s     ## default schrijf iedere 60 seconden de modbus-data uit de uart weg naar de sensoren hieronder

sensor:
# lees 40 keer met modbus-functie 0x03 (3) - Read Holding Registers uit de Quatt-modbus registers: 2999 tot en met 3039    
# lees vier keer met modbus-functie 0x06 (6) - Write Single Register uit de Quatt-modbus registers: 1999, 2010, 2015 en 3999    

- platform: modbus_controller
  modbus_controller_id: modbus_device_1
  name: "modbus_temp_outside"
  register_type: holding
  address: 2110    ## address of the register inside the Modbus slave device
  unit_of_measurement: "°C"
  accuracy_decimals: 2
  filters:
    - offset: -3000
    - multiply: 0.01
    - clamp:
        min_value: 0
        max_value: 100
        ignore_out_of_range: true

- platform: modbus_controller
  modbus_controller_id: modbus_device_1
  name: "modbus_temp_2111"
  register_type: holding
  address: 2111    ## address of the register inside the Modbus slave device
  unit_of_measurement: "°C"
  accuracy_decimals: 2
  filters:
    - offset: -3000
    - multiply: 0.01
    - clamp:
        min_value: 0
        max_value: 100
        ignore_out_of_range: true    

- platform: modbus_controller
  modbus_controller_id: modbus_device_1
  name: "modbus_temp_2112"
  register_type: holding
  address: 2112    ## address of the register inside the Modbus slave device
  unit_of_measurement: "°C"
  accuracy_decimals: 2
  filters:
    - offset: -3000
    - multiply: 0.01
    - clamp:
        min_value: 0
        max_value: 100
        ignore_out_of_range: true

- platform: modbus_controller
  modbus_controller_id: modbus_device_1
  name: "modbus_temp_2113"
  register_type: holding
  address: 2113    ## address of the register inside the Modbus slave device
  unit_of_measurement: "°C"
  accuracy_decimals: 2
  filters:
    - offset: -3000
    - multiply: 0.01
    - clamp:
        min_value: 0
        max_value: 100
        ignore_out_of_range: true

- platform: modbus_controller
  modbus_controller_id: modbus_device_1
  name: "modbus_temp_2131"
  register_type: holding
  address: 2131    ## address of the register inside the Modbus slave device
  unit_of_measurement: "°C"
  accuracy_decimals: 2
  filters:
    - offset: -3000
    - multiply: 0.01
    - clamp:
        min_value: 0
        max_value: 100
        ignore_out_of_range: true

- platform: modbus_controller
  modbus_controller_id: modbus_device_1
  name: "modbus_temp_2132"
  register_type: holding
  address: 2132    ## address of the register inside the Modbus slave device
  unit_of_measurement: "°C"
  accuracy_decimals: 2
  filters:
    - offset: -3000
    - multiply: 0.01
    - clamp:
        min_value: 0
        max_value: 100
        ignore_out_of_range: true

- platform: modbus_controller
  modbus_controller_id: modbus_device_1
  name: "modbus_temp_Water_In"
  register_type: holding
  address: 2133    ## address of the register inside the Modbus slave device
  unit_of_measurement: "°C"
  accuracy_decimals: 2
  filters:
    - offset: -3000
    - multiply: 0.01
    - clamp:
        min_value: 0
        max_value: 100
        ignore_out_of_range: true

- platform: modbus_controller
  modbus_controller_id: modbus_device_1
  name: "modbus_temp_Water_Out"
  register_type: holding
  address: 2134    ## address of the register inside the Modbus slave device
  unit_of_measurement: "°C"
  accuracy_decimals: 2
  filters:
    - offset: -3000
    - multiply: 0.01
    - clamp:
        min_value: 0
        max_value: 100
        ignore_out_of_range: true

- platform: modbus_controller
  modbus_controller_id: modbus_device_1
  name: "modbus_temp_2135"
  register_type: holding
  address: 2135    ## address of the register inside the Modbus slave device
  unit_of_measurement: "°C"
  accuracy_decimals: 2
  filters:
    - offset: -3000
    - multiply: 0.01
    - clamp:
        min_value: 0
        max_value: 100
        ignore_out_of_range: true    

- platform: modbus_controller
  modbus_controller_id: modbus_device_1
  name: "modbus_pump"
  register_type: holding
  address: 2137    ## address of the register inside the Modbus slave device
  unit_of_measurement: "W"
  accuracy_decimals: 2
  filters:
    - multiply: 0.1

- platform: modbus_controller
  modbus_controller_id: modbus_device_1
  name: "modbus_flow"
  register_type: holding
  address: 2138    ## address of the register inside the Modbus slave device
  unit_of_measurement: "l/h"
  accuracy_decimals: 2
  filters:
    - multiply: 0.618

- platform: modbus_controller
  modbus_controller_id: modbus_device_1
  name: "modbus_comprfreq_demand"
  register_type: holding
  address: 2102    ## address of the register inside the Modbus slave device
  unit_of_measurement: "Hz"
  accuracy_decimals: 0
  filters:
    - multiply: 1
    - clamp:
        min_value: 0
        max_value: 100
        ignore_out_of_range: true

- platform: modbus_controller
  modbus_controller_id: modbus_device_1
  name: "modbus_comprfreq_value"
  register_type: holding
  address: 2103    ## address of the register inside the Modbus slave device
  unit_of_measurement: "Hz"
  accuracy_decimals: 0
  filters:
    - multiply: 1
    - clamp:
        min_value: 0
        max_value: 100
        ignore_out_of_range: true

- platform: modbus_controller
  modbus_controller_id: modbus_device_1
  name: "modbus_cmd_compressorlevel"
  register_type: holding
  address: 1999

- platform: modbus_controller
  modbus_controller_id: modbus_device_1
  name: "modbus_cmd_pumpmode"
  register_type: holding
  address: 2010

- platform: modbus_controller
  modbus_controller_id: modbus_device_1
  name: "modbus_cmd_pumplevel"
  register_type: holding
  address: 2015

- platform: modbus_controller
  modbus_controller_id: modbus_device_1
  name: "modbus_cmd_workmode"
  register_type: holding
  address: 3999

